### ISSUE TITLE
Prošnja: Pushanje in commitanje kode iz zadnjih vaj

### ISSUE THREAD

**Issue by tjazerzen** [jO-Osko/Vislice-vaje2021#4]
Dober dan!

Ugotovil sem, da mi v datoteki vislice.py od zadnjih vaj koda ne deluje kot bi morala.
Zanima me, če bi lahko objavili kodo iz zadnjih vaj, da bi ugotovil svojo napako.

Hvala in zabavno programiranje,
Tjaž Eržen

**Comment by jO-Osko** [comment]
Vaje so objavljene na dveh različnih vejah:
- https://github.com/jO-Osko/Vislice-vaje2021/tree/vaje-pon
- https://github.com/jO-Osko/Vislice-vaje2021/tree/vaje-torek

Če imate pa še kakšno vprašanje pa kar na dan z njim.

Filip

**Comment by tjazerzen** [comment]
> Vaje so objavljene na dveh različnih vejah:
> 
> * https://github.com/jO-Osko/Vislice-vaje2021/tree/vaje-pon
> * https://github.com/jO-Osko/Vislice-vaje2021/tree/vaje-torek
> 
> Če imate pa še kakšno vprašanje pa kar na dan z njim.
> 
> Filip

Hvala! Po mojem bo šlo.

lpt
