### ISSUE TITLE
Vprašanje: Konzultacija za seminarsko nalogo

### ISSUE THREAD

**Issue by tjazerzen** [jO-Osko/Vislice-vaje2021#5]
Dober dan!

Žal nisem uspel najti vašega gmaila, zato vas kontaktiram preko GitHub-a.

V ponedeljek ste pred vajami za Uvod v Programiranje omenili, da bo naslednji teden možnost konzultacije za našo seminarsko nalogo (če to želimo ter se dovolj zgodaj z vami dogovorimo). Zanima me, če je ta možnost še vedno odprta.

Link do mojega repozitorija: https://github.com/tjazerzen/Najkrajsa-Do-Faksa. Naj omenim, da bo končni projekt do konca tedna verjetno še rahlo spremenjen.

Bi bilo srečanje možno v ponedeljek, 31. 5. 2021 ob 16:00?

Hvala,

Tjaž Eržen, študent 1. letnika finančne matematike

**Comment by jO-Osko** [comment]
Živjo

Bi se lahko zmenila prek emaila: ime.priimek@fmf.uni-lj.si

Filip Koprivec
